In [7]:
import pandas as pd

In [8]:
df1 = pd.read_csv("coronaTrain.csv")

In [9]:
df1.head()

,Index,0,1,2,3,4,5,6,7,8,...,991,992,993,994,995,996,997,998,999,status
0,0,5280.167730,3837.700942,1681.942638,5843.046523,-232.842418,818.394788,3030.753422,2277.569997,573.577558,...,-11.788928,-4.290970,2.594959,-43.219612,-4.240717,31.517564,-41.453802,17.277788,-20.736469,0
1,1,-3223.055169,-1115.166494,-1336.564180,1286.738497,3403.835973,1036.306212,-401.889306,323.775792,1494.498731,...,-86.010820,-31.261799,103.364060,46.960054,-62.536342,-92.178920,-39.621644,-7.973821,-30.334445,1
2,2,8007.313938,5491.331210,3663.342202,593.011444,-2989.930294,-1650.875980,1118.997993,2391.424050,2575.013614,...,20.228240,-22.978302,-68.078558,-10.060078,-19.974270,43.649501,-40.868866,-88.093409,7.586640,0
3,3,4533.969789,1859.902341,-2106.670412,-2938.184416,-1435.850576,-1167.242348,-476.518632,-215.481546,-1838.518402,...,-0.340331,-47.293885,-7.099134,-1.138214,-2.997165,20.675353,5.936402,80.723711,-58.106523,1
4,4,921.522640,-1200.312956,-14.678130,1779.298398,-3506.129638,855.198666,-943.207950,-1956.808320,320.996880,...,20.692532,-90.675207,-25.654549,46.343281,-9.284992,82.467545,13.337126,-61.225668,15.347131,1

In [10]:
df1.describe()

,Index,0,1,2,3,4,5,6,7,8,...,991,992,993,994,995,996,997,998,999,status
count,1287.000000,1287.000000,1287.000000,1287.000000,1287.000000,1287.000000,1287.000000,1287.000000,1287.000000,1287.000000,...,1287.000000,1287.000000,1287.000000,1287.000000,1287.000000,1287.000000,1287.000000,1287.000000,1287.000000,1287.000000
mean,643.000000,1629.098095,1990.819567,1129.283941,50.724176,-42.459297,21.285173,221.591514,404.007616,72.077234,...,1.771510,-1.148491,-0.735318,-1.235064,1.288617,-1.504959,-1.713376,-3.739277,-0.367846,1.019425
std,371.669208,5161.980318,4386.405249,2773.048383,2213.418151,1888.550271,1651.832354,1798.487178,1523.901642,1290.994611,...,48.130438,48.139502,46.905048,45.579178,46.774481,44.948367,46.628345,45.271536,47.726086,0.815153
min,0.000000,-14305.512737,-9052.749078,-6568.470114,-5463.788448,-6037.460920,-6223.871008,-5548.016126,-4010.621339,-4385.944058,...,-166.771585,-162.303174,-184.848157,-144.093777,-130.823342,-160.377882,-179.272128,-151.093316,-163.556749,0.000000
25%,321.500000,-2093.950549,-1373.121974,-862.786547,-1470.065274,-1205.793602,-976.729323,-958.509848,-661.350062,-812.930674,...,-28.428370,-30.903691,-33.199479,-30.819898,-28.994233,-30.651926,-31.151780,-31.709577,-30.554923,0.000000
50%,643.000000,1369.815359,1699.172706,1209.078736,-60.637738,-5.482826,22.911833,202.564172,286.946388,107.666520,...,3.609427,-1.395840,-0.425912,-2.212247,1.927339,-2.505277,-0.252321,-4.495780,1.926758,1.000000
75%,964.500000,5022.737447,5088.797048,3174.698825,1386.727350,1101.876149,1086.909122,1435.455498,1356.705754,906.235568,...,33.905273,30.652899,29.397300,27.008235,29.834532,25.661332,27.829954,23.644932,27.975106,2.000000
max,1286.000000,17158.741535,11613.745033,8343.134549,8194.672686,8032.994089,6218.467270,6603.271928,6061.324441,4930.807227,...,178.458469,204.770039,156.361219,179.626540,218.162690,203.589050,192.921893,137.153708,192.886075,2.000000

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
y = df1['status']
df1.drop(['status'],axis=1,inplace=True)
df1.set_index('Index',inplace=True)
X = df1

In [13]:
s = StandardScaler()
X_ = s.fit_transform(X)

In [29]:
y.value_counts()

2    440
1    432
0    415
Name: status, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.1)

In [16]:
Y_train

1142    2
1047    2
785     1
225     0
1182    1
       ..
1168    0
130     1
828     1
739     1
1081    0
Name: status, Length: 1158, dtype: int64

In [17]:
import xgboost as xgb

In [18]:
D_train = xgb.DMatrix(X_train, label=Y_train)
D_test = xgb.DMatrix(X_test, label=Y_test)

In [25]:
Y_train

1142    2
1047    2
785     1
225     0
1182    1
       ..
1168    0
130     1
828     1
739     1
1081    0
Name: status, Length: 1158, dtype: int64

In [30]:
param = {
    'eta': 0.3, 
    'max_depth': 3,  
    'objective': 'multi:softprob',  
    'num_class': 3} 

steps = 20  # The number of training iterations

In [31]:
D_train

In [32]:
model = xgb.train(param, D_train, steps)

In [40]:
import numpy as np
from sklearn.metrics import precision_score, recall_score, accuracy_score

preds = model.predict(D_test)
best_preds = np.asarray([np.argmax(line) for line in preds])

print("Precision = {}".format(precision_score(Y_test, best_preds, average='macro')))
print("Recall = {}".format(recall_score(Y_test, best_preds, average='macro')))
print("Accuracy = {}".format(accuracy_score(Y_test, best_preds)))

Precision = 0.9247863247863247
Recall = 0.9249180770919901
Accuracy = 0.9224806201550387

In [34]:
from sklearn.model_selection import GridSearchCV

clf = xgb.XGBClassifier()
parameters = {
     "eta"    : [0.05, 0.10, 0.15, 0.20, 0.25, 0.30 ] ,
     "max_depth"        : [ 3, 4, 5, 6, 8, 10, 12, 15],
     "min_child_weight" : [ 1, 3, 5, 7 ],
     "gamma"            : [ 0.0, 0.1, 0.2 , 0.3, 0.4 ],
     "colsample_bytree" : [ 0.3, 0.4, 0.5 , 0.7 ]
     }

grid = GridSearchCV(clf,
                    parameters, n_jobs=4,
                    scoring="neg_log_loss",
                    cv=3)

grid.fit(X_train, Y_train)

KeyboardInterrupt:

In [ ]:
model.dump_model('dump.raw.txt')

In [35]:
grid

GridSearchCV(cv=3, error_score=nan,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, gamma=None,
                                     gpu_id=None, importance_type='gain',
                                     interaction_constraints=None,
                                     learning_rate=None, max_delta_step=None,
                                     max_depth=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     n_estim...
                                     subsample=None, tree_method=None,
                                     validate_parameters=False,
                                     verbosity=None),
             iid='deprecated', n_jobs=4,
             param_grid={'colsample_bytree': [0.3, 0.4, 0.5, 0.7],
                         'eta': [0.05, 0.1, 0.15, 0.2, 0.25, 0.3],
                         'gamma': [0.0, 0.1, 0.2, 0.3, 0.4],
                         'max_depth': [3, 4, 5, 6, 8, 10, 12, 15],
                         'min_child_weight': [1, 3, 5, 7]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_log_loss', verbose=0)

In [39]:
 print(grid)

GridSearchCV(cv=3, error_score=nan,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, gamma=None,
                                     gpu_id=None, importance_type='gain',
                                     interaction_constraints=None,
                                     learning_rate=None, max_delta_step=None,
                                     max_depth=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     n_estim...
                                     subsample=None, tree_method=None,
                                     validate_parameters=False,
                                     verbosity=None),
             iid='deprecated', n_jobs=4,
             param_grid={'colsample_bytree': [0.3, 0.4, 0.5, 0.7],
                         'eta': [0.05, 0.1, 0.15, 0.2, 0.25, 0.3],
                         'gamma': [0.0, 0.1, 0.2, 0.3, 0.4],
                         'max_depth': [3, 4, 5, 6, 8, 10, 12, 15],
                         'min_child_weight': [1, 3, 5, 7]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_log_loss', verbose=0)

In [41]:
test = pd.read_csv("coronaTest.csv")

In [42]:
test.head()

,Index,0,1,2,3,4,5,6,7,8,...,990,991,992,993,994,995,996,997,998,999
0,0,2360.468121,3170.244556,1697.758472,5598.597705,-1122.907590,980.658815,1178.046905,3296.901426,549.362795,...,31.733982,18.159848,62.793697,26.542204,20.632675,11.898688,24.426936,12.326023,2.524550,23.820559
1,1,9824.143037,3357.881942,201.543848,3019.119601,-4953.704512,-666.601915,192.440353,4142.487313,2262.905200,...,6.011481,46.987701,-23.835829,14.808673,5.638663,-16.839797,20.230744,-1.293179,82.583835,59.123195
2,2,2341.483987,1972.182132,5321.074820,2076.880657,-1057.674537,550.924115,2006.304348,-920.764523,-639.762922,...,29.900149,-16.289829,-31.641735,-11.114851,-2.929377,-58.487379,6.710407,1.146231,24.553120,-35.122233
3,3,9588.800823,10121.225552,7233.253861,-495.263472,-1506.855675,2146.521265,-2909.550994,878.050546,2200.871095,...,18.709080,8.423986,5.825512,-41.753367,-16.802495,-25.847536,-25.330617,13.822268,10.729671,-5.975498
4,4,2902.667817,2847.755305,3424.176309,5046.393309,-1387.708023,-1713.565415,3364.930083,-253.248893,-3011.743840,...,26.846112,52.430472,102.027308,-72.852526,-24.766511,26.342181,-18.998844,18.412844,-0.115226,15.015220

In [43]:
s=test['Index']
test.drop(["Index"],axis=1,inplace=True)

In [44]:
test

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,2360.468121,3170.244556,1697.758472,5598.597705,-1122.907590,980.658815,1178.046905,3296.901426,549.362795,49.595597,...,31.733982,18.159848,62.793697,26.542204,20.632675,11.898688,24.426936,12.326023,2.524550,23.820559
1,9824.143037,3357.881942,201.543848,3019.119601,-4953.704512,-666.601915,192.440353,4142.487313,2262.905200,3473.093884,...,6.011481,46.987701,-23.835829,14.808673,5.638663,-16.839797,20.230744,-1.293179,82.583835,59.123195
2,2341.483987,1972.182132,5321.074820,2076.880657,-1057.674537,550.924115,2006.304348,-920.764523,-639.762922,1050.404691,...,29.900149,-16.289829,-31.641735,-11.114851,-2.929377,-58.487379,6.710407,1.146231,24.553120,-35.122233
3,9588.800823,10121.225552,7233.253861,-495.263472,-1506.855675,2146.521265,-2909.550994,878.050546,2200.871095,-1471.991097,...,18.709080,8.423986,5.825512,-41.753367,-16.802495,-25.847536,-25.330617,13.822268,10.729671,-5.975498
4,2902.667817,2847.755305,3424.176309,5046.393309,-1387.708023,-1713.565415,3364.930083,-253.248893,-3011.743840,3458.805993,...,26.846112,52.430472,102.027308,-72.852526,-24.766511,26.342181,-18.998844,18.412844,-0.115226,15.015220
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1327,1669.625910,3233.945941,3580.337815,4926.369230,-2966.888472,122.270191,379.868420,2710.460032,-533.676044,1287.622903,...,31.787269,-62.329069,-9.871753,8.680603,-88.553351,16.560707,32.371401,-44.517140,-50.361741,-50.784598
1328,141.382463,3556.621564,1552.948763,3093.796895,-3482.213752,1298.344833,-2521.738622,2530.125618,-596.336250,458.583166,...,11.558813,31.727545,30.375693,18.589092,-65.447549,30.498736,52.635948,21.557195,3.929870,46.270275
1329,-166.359082,10991.967612,3413.756983,-3102.171249,-235.979488,-211.637843,-635.319531,711.588389,862.129487,-1748.045255,...,36.402787,52.672611,-19.224483,-53.844409,-9.161385,-7.539913,78.065800,-1.326272,33.332012,56.553624
1330,-10577.031218,8488.702355,729.906274,-198.058544,-2122.613429,-3206.070515,-484.106762,280.659408,-610.098246,-2228.664466,...,-51.440818,-51.302630,1.332210,31.587702,-17.434374,54.993412,-14.058313,-8.917321,-13.908197,36.128611
1331,6132.560809,4110.473898,1956.069294,7405.633424,-634.536813,371.823518,3664.123671,3016.833316,1557.705246,53.761981,...,-43.330077,-16.190095,7.477157,27.657959,-13.155145,-38.569694,47.617274,-76.723835,25.390537,-25.244336

In [56]:
D_test_1 = xgb.DMatrix(test)

In [58]:
results = model.predict(D_test_1)

In [59]:
A=[]
for i in results :
    x = list(i).index(max(list(i)))
    A.append(x)

In [54]:
results = np.max(results,axis=0)

In [61]:
df = pd.DataFrame({'status':A})

In [64]:
df

      status
0          0
1          0
2          2
3          0
4          0
...      ...
1327       0
1328       0
1329       0
1330       1
1331       0

[1332 rows x 1 columns]

In [65]:
df.to_csv('submit.csv')